- name: Setup Systemd Networking
  import_tasks: enable_services.yml
  tags:
    - install
    - networking

- name: Disable NetworkManager
  import_tasks: disable_network_manager.yml
  tags:
    - networking