---
- name: ensure Xorg is installed correctly
  apt: name=xorg state=latest
- name: "Install X dependencies"
  apt:
    pkg:
    # basic X server
      - xserver-xorg
      - lightdm
    state: present
    update_cache: no
    install_recommends: no
- name: "Enable lightdm autologin"
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: ".*autologin-user\\s*=\\s*($|quelab)"
    line: "autologin-user = quelab"    
- name: "Do not blank X screen"
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: ".*xerver-command=.*"
    line: "xserver-command=X -s 0 dpms"    
- name: ensure nodm is absent
  apt:  name=nodm state=absent
- name: ensure firefox-esr is installed
  apt:  name=firefox-esr state=latest
- name: ensure chromium is installed for kiosk mode
  apt: name=chromium state=latest
- name: add quelab user
  user: name=quelab password="{{quelab_password}}"
- name: Setup nodm user as quelab
  lineinfile:
    dest: /etc/default/nodm
    regexp: '^NODM_USER='
    line: 'NODM_USER=quelab'
- name: Setup chromium to run by default in kiosk mode
  blockinfile:
    dest: /home/quelab/.xsession
    create: yes
    owner: quelab
    group: quelab
    block: |
      #!/usr/bin/bash
      # xset dpms 0 0 0 && xset s noblank && xset s off
      # DISPLAY=:0 xset dpms force on
      # raspad 1280x800
      chromium --start-maximized --disable-session-crashed-bubble --disable-infobars --window-position=0,0 --window-size=1280,800 --kiosk http://localhost:8888

