- hosts: all
  remote_user: admin
  become: yes
  become_method: sudo
  vars_files:
    - ../vars/doorctrl.yml
  vars:
    # wild_apricot_api_key: 4fy63rfn598ip4svqkse8ic7eb9rcv
    wild_apricot_api_key: "{{vault_wild_apricot_api_key}}"
    quelab_password: "{{vault_quelab_password}}"
    quelab_psk: "{{vault_quelab_psk}}"
    cactus_psk: "{{vault_cactus_psk}}"
  roles:
    - kiosk
    - quelab_signin
    - quelab_rfid_monitor
    - mosquitto
    - quelab_wifi
    - debian_systemd_network





